const FETCH_USER = "FETCH_USER"
const FETCH_ALL_USERS = "FETCH_ALL_USERS"
const FETCH_VENUE = "FETCH_VENUE"
const FETCH_ALL_VENUES = "FETCH_ALL_VENUES"
const FETCH_EVENT = "FETCH_EVENT"
const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS"
const LOG_IN = "LOG_IN"
const LOG_OUT = "LOG_OUT"
const CREATE_USER = "CREATE_USER"
const UPDATE_USER = "UPDATE_USER"
const MAKE_REQUEST = "MAKE_REQUEST"
const ADD_FRIEND = "ADD_FRIEND"



export {
  FETCH_USER,
  FETCH_ALL_USERS,
  FETCH_VENUE,
  FETCH_ALL_VENUES,
  FETCH_EVENT,
  FETCH_ALL_EVENTS,
  LOG_IN,
  LOG_OUT,
  CREATE_USER,
  UPDATE_USER,
  MAKE_REQUEST,
  ADD_FRIEND
}
