const FETCH_USER = "FETCH_USER"
const FETCH_ALL_USERS = "FETCH_ALL_USERS"
const FETCH_VENUE = "FETCH_VENUE"
const FETCH_ALL_VENUES = "FETCH_ALL_VENUES"
const FETCH_EVENTS = "FETCH_EVENTS"
const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS"
const LOG_IN = "LOG_IN"
const CREATE_USER = "CREATE_USER"

export {
  FETCH_USER,
  FETCH_ALL_USERS,
  FETCH_VENUE,
  FETCH_ALL_VENUES,
  FETCH_EVENTS,
  FETCH_ALL_EVENTS,
  LOG_IN,
  CREATE_USER
}
