const FETCH_USER = "FETCH_USER"
const FETCH_ALL_USERS = "FETCH_ALL_USERS"
const FETCH_VENUE = "FETCH_VENUE"
const FETCH_ALL_VENUES = "FETCH_ALL_VENUES"
const FETCH_EVENTS = "FETCH_EVENTS"
const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS"

export {
  FETCH_USER,
  FETCH_ALL_USERS,
  FETCH_VENUE,
  FETCH_ALL_VENUES,
  FETCH_EVENTS,
  FETCH_ALL_EVENTS
}
